version: 0.2

phases:
  build:
    commands:
      - echo Nothing to yet
artifacts:
  files:
    - 'images/*'
    - 'index.html'
    - 'favicon.ico'
    - 'main.css'
  name: hughbuild.zip-$(date +%Y-%m-%d)
